# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: publish

on:
  push:
    branches:
      - main

jobs:
  npm:
    name: publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
  
  github_p:
        name: Publish to gp
        permissions:
            contents: read
            packages: write
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: 16
                  registry-url: 'https://npm.pkg.github.com'
                  cache: npm
          
            
            - name: Publish to github registry
              run: |
                # Change publish registry
                echo "$(jq '.publishConfig.registry = "https://npm.pkg.github.com"' package.json)" > package.json
                # Add organisation scope to package name
                echo "$( jq '.name = "@magnuscardell/zenfuse"' package.json )" > package.json
                # And publish this boy 
                npm publish --@magnuscardell:registry=https://npm.pkg.github.com

              env:
                  NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
